### ISSUE TITLE
Weird default graph settings for new plugins

### ISSUE THREAD

**Issue by stephan-gh** [Hidendra/mcstats.org#22]
Previously, when a new plugin was added to MCStats they always had the default graphs (rank, server software, operating system...) configured automatically. Currently it seems like all graphs are disabled for new plugins by default, only showing the user count at the top.

For example my plugin [ServerListPlus](http://mcstats.org/plugin/ServerListPlus) which was added on MCStats long ago has them configured properly, even though I never touched the settings. For new plugins (e.g. [NostalgiaGen](http://mcstats.org/plugin/NostalgiaGen)) this seems to be different:

When I go to the admin page for ServerListPlus I can't even disable nor change any of them (and they're set up correctly), however if I go to the admin page of NostalgiaGen the graphs were available but all disabled, with wrong types set to them and in random order. I tried to copy the settings from ServerListPlus, but even then it didn't seem to set everything correctly: http://mcstats.org/plugin/NostalgiaGen

Is there any special reason for this?

**Comment by Hidendra** [comment]
It looks like the cron job that fixes graphs wasn't configured. I've updated my ansible scripts to ensure the cron is created, and also ran it now, so the graphs on NostalgiaGen look correct now.

Sorry, I didn't look at the graph settings for NostalgiaGen before fixing them, so can't say exactly why it didn't look right after you copied the settings from ServerListPlus. On my end, the cron that fixes graphs periodically just updates settings for default graphs to what they should be.
