### ISSUE TITLE
Plugin Ownership Request

### ISSUE THREAD

**Issue by ThunderGemios10** [Hidendra/mcstats.org#24]
@Hidendra Can you please approve ownership requests? I have been waiting for 2-3 months now.
And you seem active on GitHub.

**Comment by boomboompower** [comment]
@ThunderGemios10 How about this http://prntscr.com/bgmv4z/direct

**Comment by ThunderGemios10** [comment]
@boomboompower Wow so long .-. I guess we can say that MCStats is now inactive. Well the website is still up but the author is inactive. The author should hire moderators to approve/reject requests on the website. @Hidendra
