### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by cyberpwnn** [Hidendra/mcstats.org#28]
Tested and asked others to test. Its just a black screen.

**Comment by boomboompower** [comment]
@cyberpwnn Not anymore, please close this issue.

**Comment by KevinNovak** [comment]
I'm also seeing this on my plugins page: [http://mcstats.org/plugin/DeathFeathers](http://mcstats.org/plugin/DeathFeathers)
Tried multiple browsers, same issue.
