### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by alfalfascout** [Hidendra/mcstats.org#31]
I'm getting a lot of internal server errors, bad gateway errors, etc. when all I'm trying to do is browse the site.

**Comment by ghost** [comment]
This project is slowly dying, and has been for the past years.

**Comment by alfalfascout** [comment]
Aww, I was hoping to use mcstats in my plugin. Any chance someone else might take up hosting the service?

**Comment by SystemUpdate** [comment]
Ill work on getting my own version up soon however I don't have the database so all the tracked data would be gone and it's gonna be hard getting it distrusted

**Comment by sgdc3** [comment]
#34

**Comment by sgdc3** [comment]
@alfalfascout The service is online again, could you close the issue please? :)
