### ISSUE TITLE
mcstats.org offline - error 500 or ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Janmm14** [Hidendra/mcstats.org#32]

**Comment by fdatoo** [comment]
This happens all the time, I hope the issue is resolved soon.

**Comment by nootsponge** [comment]
Could it be the host?

**Comment by sgdc3** [comment]
#34

**Comment by sgdc3** [comment]
@Janmm14 You should close the issue now, the service is online again

**Comment by sgdc3** [comment]
@Janmm14 and remember to join the StatsCraft skype group: https://join.skype.com/cc27PEArdQwo
