### ISSUE TITLE
Website Down Spamming Console

### ISSUE THREAD

**Issue by KenaiTheWolf** [Hidendra/mcstats.org#33]
Every time this site goes down my console is plagued with 500 & 504 errors. I wish there were a plugin to suppress mcstats errors.

**Comment by sgdc3** [comment]
it should already suppress errors :/

**Comment by KenaiTheWolf** [comment]
I still get:
"[Metrics] Unexpected end of file from server" or
"[Metrics] Server returned HTTP response code: 500 for URL"

**Comment by sgdc3** [comment]
... the community should take over the project

**Comment by sgdc3** [comment]
#34

**Comment by sgdc3** [comment]
Service is online again, @The-Wolf312 please close the issue

**Comment by KenaiTheWolf** [comment]
I'm turning notifications for this off.

**Comment by KenaiTheWolf** [comment]
This project seems abandoned.

**Comment by sgdc3** [comment]
That's why we started statscraft ;)

**Comment by KenaiTheWolf** [comment]
Well that doesn't stop old plugins that haven't been updated in three years from trying to use this.

**Comment by sgdc3** [comment]
We'll see ;)
