### ISSUE TITLE
Let's continue the project, who wants to join?

### ISSUE THREAD

**Issue by sgdc3** [Hidendra/mcstats.org#34]
Hello, i think we should start considering taking over mcstats, this is a very useful service for the entire minecraft modding community, we can't let it die!

Who want's to join the project? ;)

Organization: https://github.com/MCStatsReborn

Current members:
- @sgdc3 - Developer, Manager
- @Chnkr - Developer
- @SystemUpdate - Developer
- @SirFaizdat - Web developer
- @Janmm14  - Web developer
- @f14stelt - Sponsor, Sysadmin: I can provide a 12 core server with an excellent DDOS protection

Contact me if you want to join the team!

**Comment by sgdc3** [comment]
Just poking some people:
@Hidendra @inventivetalentdev @Yive @ljacqu @games647

**Comment by sgdc3** [comment]
Requirements:

Staff:
- Web developers
- Metrics plugin/library developers
- Administrators
- Support team

Random stuff:
- Forum
- CI Service + Maven repository

**Comment by sgdc3** [comment]
Todo list:
- [ ] Reach the minimum amount of people to maintain the service
- [ ] Contact @Hidendra 
- [ ] Setup the server OS and secure the access
- [ ] Setup a working server instance
- [ ] Update Plugin-Metrics
- [ ] Setup the assistance forum
- [ ] Obtain access to the domain
- [ ] Start working on a complete new version of mcstats

**Comment by sgdc3** [comment]
Contacts:
- Gitter: https://gitter.im/mcstatsreborn/MCStats
- IRC: irc://irc.esper.net/metrics

**Comment by sgdc3** [comment]
#placeholder

**Comment by sgdc3** [comment]
#placeholder

**Comment by sgdc3** [comment]
Just poking some people:
@Hidendra @inventivetalentdev @Yive @ljacqu @games647

**Comment by sgdc3** [comment]
@SystemUpdate

**Comment by ghost** [comment]
I'd be willing to invest a basic amount of time, but i don't think that we would need to clone mcstats.org! I'd suggest building a new project with new and interesting features.

**Comment by sgdc3** [comment]
@Chnkr I agree with you but we need to provide the old mcstats until the new version is completed.
Anyway i would like to keep the name and the domain + keep legacy support for the current reporting API

**Comment by sgdc3** [comment]
Anyway j would like to keep the name and the domain + keep legacy support for the current report library ;)

**Comment by sgdc3** [comment]
@Chnkr Anyway, how would you like to contribute? Web interface and/or Server instance and/or Reporting library?

**Comment by SystemUpdate** [comment]
I've already contacted my sponsor about  sponsoring a project, but I'm in if they can't provide

**Comment by SystemUpdate** [comment]
(Sorry for double posting) as for ddos protection, i was just gonna drop it behind CloudFlare which would resolve that issue. 

I doubt we would be able to get the domain though

**Comment by sgdc3** [comment]
@SystemUpdate the specs of the machine are very impressive, 12 core intel cpu, y
64gb of ram, 10Gbit NIC ;)

**Comment by sgdc3** [comment]
@SystemUpdate Yeah, i agree with you  but i rhibk that an additional latency-free protection is good anyway ;) We should be able to turn off cloudflare if there are any issues

**Comment by sgdc3** [comment]
We should be able to turn off cloudflare if there are any issues

**Comment by sgdc3** [comment]
@SystemUpdate how would you like to contribute? :)

**Comment by fdatoo** [comment]
I'd love to provide my web development skills if necessary.

**Comment by SystemUpdate** [comment]
@sgdc3 developer, I know basics of Linux and pr / dns / stuff like that

**Comment by Janmm14** [comment]
I could help out also with some web development (php and frontend langs) and basics of linux.

There is also no latency-free protection and cloudflare would make the web page be much more stable, api could be on a subdomain or whatever.

**Comment by sgdc3** [comment]
@Janmm14 0.5 ms latency can be omitted ;)

**Comment by sgdc3** [comment]
I think we can use cloudflare dor the web interface and the Ddos protections for the api

**Comment by sgdc3** [comment]
Wait! It's up again! @Hidendra are you there? ;)

**Comment by nootsponge** [comment]
@sgdc3 It's like a roller coaster, up and down.

**Comment by sgdc3** [comment]
@WolfieGaming That's why we should help @Hidendra keep it updated ;)

**Comment by SystemUpdate** [comment]
@sgdc3 no point in using cloudflare for one bit but not the other, if you gonna use it you might as well use it overall otherwise it defeats the point.

**Comment by sgdc3** [comment]
Sorry @Hidendra , as probably you noticed English is not my native language and i realized too late that "take over" is a little aggressive term. We love your work and we would be pleased to have you in this project :)

**Comment by sgdc3** [comment]
Can't use cloudflare because @Hidendra will be the only owner of the domain anyway.

**Comment by Janmm14** [comment]
I don't know the extend of your continuation thoughts, but I thought we would have a different domain if hidendra is not available.

**Comment by sgdc3** [comment]
i know, i'm having a discussion with @jamierocks on the paper irc, if you want to join the discussion

**Comment by nootsponge** [comment]
I'm excited for this. Hope it works out! I'll keep checking to see when it gets finished!

**Comment by sgdc3** [comment]
Closing this as we can't use @Hidendra 's sources die to licensing. We'll create our own service from scratch. Org: https://github.com/StatsCraft-MC

**Comment by MatthewSH** [comment]
Guessing this thought died out too? Honestly guys, you're putting way too much into the simple stuff. I don't know why I'm bumping this but meh. Oh well.

Seriously. DDoS protection? Server? Sponsorship? Do you even have the software yet? Write the software, then worry about the server. :wink:

**Comment by sgdc3** [comment]
We finished the metrics service (bukkit side) but then when we started working on the backend nobody had experience with the spring framework. I don't completely agree with your idea: if the project has no factibility what's the sense of coding houndreds and houndreds off lines of code? The MC community is full of kids with ddos botnets and dedicated stressers, a minimal protection is needed, at least here in europe. About the sponsorship: do you know the abmount of requests thatcstats needs to handle every minute? The HW cost is one huge problem, start searching for a good sponsor is one of the first thing you should do.

**Comment by Janmm14** [comment]
There was one dev in the team knowing spring, but w/o him doing some basics I don't want to learn a new and huge framework.

Obviously one could also choose anotger backend language than java, maybe php. But the frontend requires the most work anyway, else the new service would not be used. And I don't like frontend development :/

**Comment by sgdc3** [comment]
With more developer in the team the project would probably continue. I started learning how to use spring but it's hard to create a well structured application using a new framework.

**Comment by MatthewSH** [comment]
@sgdc3 referring to your original comment. You're jumping too far ahead. How can you go to sponsors and request a sponsorship with a "we're working on" attitude when you have nothing to really show? Then what happens, well..happens. The work halts.

Build the product (not everything has to be built on the server, we have git for a reason), then worry about the server. Once you have a working product, you'll know what you need for the server. If you have a well-built system that handles things properly, you may not need the hardware you think. It's all about how you write it.

Believe me, I had to take a lot of things into account with [CapesAPI](https://capesapi.com).

**Comment by sgdc3** [comment]
I talked about the HW because i was sure i had access to that machine. The host is a friend of mine and we collaborated on many other projects.
