### ISSUE TITLE
WEBSITE

### ISSUE THREAD

**Issue by Endervines** [Hidendra/mcstats.org#37]
The website is not working.. Last time i checked (few days ago) it was perfectly working.
Anyone knows why?

**Comment by sgdc3** [comment]
:( @Hidendra

**Comment by KevinNovak** [comment]
Also here wondering why.

**Comment by Polyana-Fontes** [comment]
The maven repository is also down and making travis-ci builds to fail, some rare times the build succeeds.
http://repo.mcstats.org/

**Comment by sgdc3** [comment]
Probably an issue with the O.S. of the dedicated server...

**Comment by Endervines** [comment]
Im feeling like this project is just dieing... Its more down than up and barely gets developed and maintained. Thinking of changing to an other metrics plugin if one exists..

**Comment by KevinNovak** [comment]
Take a look at [bStats](https://bstats.org/) if you guys need an MCStats alternative. It's still in Beta but seems to provide the same functionality, while being more up-to-date.

**Comment by Endervines** [comment]
Looks good @KevinNovak ! Surely will give this a try

**Comment by Wani4ka** [comment]
It seems it's down again.

**Comment by liquiddevelopmentnet** [comment]
Its down again ...
