### ISSUE TITLE
What is your problem at providing stability?

### ISSUE THREAD

**Issue by Janmm14** [Hidendra/mcstats.org#41]
Can someone help?
Do you want help?
Is it a problem with money?
Is it a problem with time?
Should people switch to an alternate solution?
What is going on in general?
If its a database problem: I think it wouldn't be a problem to archive the current database and start with a new.
Why is the main page not going through cloudflare?

Possibly edit your blog to move jquery url to some cdn.
Update your wordpress version likely required, because of possible vulnerabilities, check your system.

You could also ask cloudflare if they provide open-source free pro plan for you.

**Comment by Janmm14** [comment]
And especially: Why does the graph generator return 0 while the image is loading?

**Comment by Janmm14** [comment]
But good job - apparantly you still handle incoming reporter stuff well enough to get some good looking graphs.

**Comment by sgdc3** [comment]
McStats now uses a very outdated stack, i think it's time to move on and start using other services.

**Comment by Janmm14** [comment]
I'm still curious to see what is happening and what the issues are.

**Comment by DoNotSpamPls** [comment]
The last real activity from the author was back in 2015. I hope he's okay and all, but we all know that making issues doesn't work. The domain expires this April, so we'll see if it gets renewed or not.

**Comment by fdatoo** [comment]
You can just switch to bStats, https://bstats.org. Much more reliable and stable.

**Comment by wyatt-herkamp** [comment]
@faizaand the annoying part with BStats is you cant get the Spigot usage statistics.

**Comment by sgdc3** [comment]
@wherkamp what do you mean?

**Comment by wyatt-herkamp** [comment]
@sgdc3 SpigotMC pushes its statistics to MCStats. And saying use Bstats you can't find the SpigotMC usage statistics on MCStats. I do use BStats for my plugins.

**Comment by Janmm14** [comment]
@wherkamp

McStats can be considered dead now.
SpigotMC will not add any other metrics provider, if there will be a new metrics endpoint, it will be owned by spigotmc. Words from md_5.

Plugins using bstats of course provide general bukkit/spigot usage. Unfortunaly it looks like the server brand is not sent.

**Comment by wyatt-herkamp** [comment]
But it is annoying because I want to know some statistics about SpigotMC. But ok

**Comment by sgdc3** [comment]
@wherkamp just stop using spigot an move to paper, for a better world xD

**Comment by sgdc3** [comment]
@Janmm14 next version of bstats will consider the various server implementations

**Comment by Janmm14** [comment]
Yeah I guess rendering graphs serverside is really outdated now in case of mcstats.

**Comment by wyatt-herkamp** [comment]
@sgdc3 I did but I want to compare the amount of Paper to Spigot servers.

**Comment by Janmm14** [comment]
@wherkamp soon you can compare the amount of spigot and paper servers which have a plugin with the new bstats version.

**Comment by ElectroBoy404NotFound** [comment]
Seems like @Hidendra is still a little active on github.

**Comment by Janmm14** [comment]
@ElectroBoy404NotFound
But at this point, with mcstats.org dns removed its clear that this project is completely dead now. Also bstats.org exists as a replacement and it seems to get sponsored long-term.

**Comment by ElectroBoy404NotFound** [comment]
> 

I know, i was just telling that the owner is now like dead rotted,
